<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Nike Ram</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>11</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>374.738149965931</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>9.458277812737226</KnownMass>
                    <Density>1049.2093265</Density>
                    <Material>Polystyrene PS</Material>
                    <Name>Nose cone</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>9.458277812737226</CalcMass>
                    <CalcCG>109.36626448145466</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>150.0</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>0</SerialNo>
                    <ShapeCode>0</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>1.016</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <BaseDia>34.036</BaseDia>
                    <ShoulderLen>12.7</ShoulderLen>
                    <ShoulderOD>33.02</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>12.19168740575165</KnownMass>
                    <Density>1121.29241</Density>
                    <Material>Paper</Material>
                    <Name>Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>12.19168740575165</CalcMass>
                    <CalcCG>101.6</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>203.2</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>1</SerialNo>
                    <OD>34.036</OD>
                    <ID>33.02</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>33.02</MotorDia>
                    <EngineOverhang>12.7</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>5.574662260746817</KnownMass>
                            <Density>128.147704</Density>
                            <Material>Balsa</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>174.625</Xb>
                            <CalcMass>5.574662260746817</CalcMass>
                            <CalcCG>25.4</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>50.8</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>2</SerialNo>
                            <OD>33.02</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>75.126</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Mass object</Name>
                            <KnownCG>165.1</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>165.1</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>18.287531108627473</KnownMass>
                    <Density>1121.29241</Density>
                    <Material>Paper</Material>
                    <Name>Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>18.287531108627473</CalcMass>
                    <CalcCG>152.4</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>304.8</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>4</SerialNo>
                    <OD>34.036</OD>
                    <ID>33.02</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>33.02</MotorDia>
                    <EngineOverhang>12.7</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <FinSet>
                            <KnownMass>2.8504558914134686</KnownMass>
                            <Density>128.147704</Density>
                            <Material>Balsa</Material>
                            <Name>Fin set</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>244.475</Xb>
                            <CalcMass>2.8504558914134686</CalcMass>
                            <CalcCG>28.521587291940765</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>5</SerialNo>
                            <FinCount>3</FinCount>
                            <RootChord>57.15</RootChord>
                            <TipChord>25.4</TipChord>
                            <SemiSpan>57.15</SemiSpan>
                            <SweepDistance>15.752464963864101</SweepDistance>
                            <Thickness>3.175</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>1</TipShapeCode>
                            <TabLength>0.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <BodyTube>
                            <KnownMass>11.869866111778784</KnownMass>
                            <Density>1121.29241</Density>
                            <Material>Paper</Material>
                            <Name>Body tube</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>190.5</Xb>
                            <CalcMass>11.869866111778784</CalcMass>
                            <CalcCG>63.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>127.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <OD>30.734</OD>
                            <ID>28.956</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>28.956</MotorDia>
                            <EngineOverhang>12.7</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts>
                                <Ring>
                                    <KnownMass>5.426224508241724</KnownMass>
                                    <Density>1121.29241</Density>
                                    <Material>Paper</Material>
                                    <Name>Engine block</Name>
                                    <KnownCG>0.0</KnownCG>
                                    <UseKnownCG>0</UseKnownCG>
                                    <Xb>0.0</Xb>
                                    <CalcMass>5.426224508241724</CalcMass>
                                    <CalcCG>6.35</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>0</LocationMode>
                                    <Len>12.7</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>7</SerialNo>
                                    <OD>28.956</OD>
                                    <ID>18.796</ID>
                                    <UsageCode>2</UsageCode>
                                    <AutoSize>0</AutoSize>
                                </Ring>
                            </AttachedParts>
                        </BodyTube>
                        <LaunchLug>
                            <KnownMass>0.947184017757213</KnownMass>
                            <Density>1121.29241</Density>
                            <Material>paper</Material>
                            <Name>Launch lug</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>79.375</Xb>
                            <CalcMass>0.947184017757213</CalcMass>
                            <CalcCG>25.4</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>50.8</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>8</SerialNo>
                            <OD>6.293</OD>
                            <ID>4.293</ID>
                        </LaunchLug>
                        <Streamer>
                            <KnownMass>0.10975452522710606</KnownMass>
                            <Density>0.0028480827214</Density>
                            <Material>Paper</Material>
                            <Name>Streamer</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>34.925</Xb>
                            <CalcMass>0.10975452522710606</CalcMass>
                            <CalcCG>31.0388</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>62.0776</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <Width>62.0776</Width>
                            <DragCoefficient>0.1</DragCoefficient>
                        </Streamer>
                        <Ring>
                            <KnownMass>6.520128278786196</KnownMass>
                            <Density>1121.29241</Density>
                            <Material>Paper</Material>
                            <Name>Ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>254.0</Xb>
                            <CalcMass>6.520128278786196</CalcMass>
                            <CalcCG>25.4</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>50.8</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>10</SerialNo>
                            <OD>33.02</OD>
                            <ID>30.734</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Parachute>
                            <KnownMass>7.975950925286614</KnownMass>
                            <Density>0.006700000000000001</Density>
                            <Material>Ripstop nylon</Material>
                            <Name>Parachute</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>7.975950925286614</CalcMass>
                            <CalcCG>12.5</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>11</SerialNo>
                            <Dia>300.0</Dia>
                            <ShroudLineCount>6</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>300.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0018</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Elastic cord (round 2 mm, 1/16 in)</ShroudLineMaterial>
                            <DragCoefficient>0.8</DragCoefficient>
                        </Parachute>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>