<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Wildman Competitor 5</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>18</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>1518.3243675483857</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>938.5776607059942</KnownMass>
                    <Density>1470.17</Density>
                    <Material>FWFG</Material>
                    <Name>Nose cone</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>938.5776607059942</CalcMass>
                    <CalcCG>505.9421817597558</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>719.328</Len>
                    <FinishCode>0</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>6</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>2.54</WallThickness>
                    <ShapeParameter>0.33</ShapeParameter>
                    <AttachedParts/>
                    <BaseDia>130.81</BaseDia>
                    <ShoulderLen>127.0</ShoulderLen>
                    <ShoulderOD>127.0</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>1092.25</KnownMass>
                    <Density>1470.17</Density>
                    <Material>FWFG</Material>
                    <Name>Payload Section</Name>
                    <KnownCG>304.8</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>691.3964266091533</CalcMass>
                    <CalcCG>304.8</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>609.6</Len>
                    <FinishCode>0</FinishCode>
                    <SerialNo>2</SerialNo>
                    <OD>130.81</OD>
                    <ID>127.0</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>127.0</MotorDia>
                    <EngineOverhang>0.5</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>529.796</KnownMass>
                            <Density>1470.17</Density>
                            <Material>FWFG</Material>
                            <Name>Tube coupler</Name>
                            <KnownCG>152.4</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-152.4</Xb>
                            <CalcMass>335.480532123161</CalcMass>
                            <CalcCG>152.4</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>304.8</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <OD>127.0</OD>
                            <ID>123.19</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>76.81640096137122</KnownMass>
                            <Density>1909.91</Density>
                            <Material>G10 fiberglass</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>152.4</Xb>
                            <CalcMass>76.81640096137122</CalcMass>
                            <CalcCG>1.5875</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>3.175</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>4</SerialNo>
                            <OD>127.0</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>72.27655166455418</KnownMass>
                            <Density>1909.91</Density>
                            <Material>G10 fiberglass</Material>
                            <Name>Coupler Bulkhead</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>149.225</Xb>
                            <CalcMass>72.27655166455418</CalcMass>
                            <CalcCG>1.5875</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>3.175</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>5</SerialNo>
                            <OD>123.19</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>72.27655166455418</KnownMass>
                            <Density>1909.91</Density>
                            <Material>G10 fiberglass</Material>
                            <Name>Coupler Bulkhead</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-152.4</Xb>
                            <CalcMass>72.27655166455418</CalcMass>
                            <CalcCG>1.5875</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>3.175</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <OD>123.19</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>76.81640096137122</KnownMass>
                            <Density>1909.91</Density>
                            <Material>G10 fiberglass</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-155.575</Xb>
                            <CalcMass>76.81640096137122</CalcMass>
                            <CalcCG>1.5875</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>3.175</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>7</SerialNo>
                            <OD>127.0</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Parachute>
                            <KnownMass>963.884</KnownMass>
                            <Density>0.006685</Density>
                            <Material>1.9 oz. Ripstop Nylon (SkyAngle)</Material>
                            <Name>Parachute</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>66.675</Xb>
                            <CalcMass>239.96053153681305</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>8</SerialNo>
                            <Dia>2100.58</Dia>
                            <ShroudLineCount>4</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>2032.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.00102</ShroudLineMassPerMM>
                            <ShroudLineMaterial>1/16 In. braided nylon</ShroudLineMaterial>
                            <DragCoefficient>1.26</DragCoefficient>
                        </Parachute>
                        <MassObject>
                            <KnownMass>544.3106208</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock Cord</Name>
                            <KnownCG>368.3</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>368.3</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>121.92</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>2184.5</KnownMass>
                    <Density>1470.17</Density>
                    <Material>FWFG</Material>
                    <Name>Body tube</Name>
                    <KnownCG>609.6</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>1382.7928532183066</CalcMass>
                    <CalcCG>609.6</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>1219.2</Len>
                    <FinishCode>0</FinishCode>
                    <SerialNo>10</SerialNo>
                    <OD>130.81</OD>
                    <ID>127.0</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>127.0</MotorDia>
                    <EngineOverhang>0.5</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <BodyTube>
                            <KnownMass>563.362</KnownMass>
                            <Density>1470.17</Density>
                            <Material>FWFG</Material>
                            <Name>98mm Motor Mount</Name>
                            <KnownCG>304.8</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>449.86179645956435</CalcMass>
                            <CalcCG>304.8</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>609.6</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>11</SerialNo>
                            <OD>102.235</OD>
                            <ID>99.06</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>99.06</MotorDia>
                            <EngineOverhang>0.5</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <Ring>
                            <KnownMass>41.053337755734255</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>Centering ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>41.053337755734255</CalcMass>
                            <CalcCG>6.35</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>12.7</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>12</SerialNo>
                            <OD>127.0</OD>
                            <ID>102.235</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>41.053337755734255</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>Centering ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>485.775</Xb>
                            <CalcMass>41.053337755734255</CalcMass>
                            <CalcCG>6.35</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>12.7</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>13</SerialNo>
                            <OD>127.0</OD>
                            <ID>102.235</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>41.053337755734255</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>Centering ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>593.725</Xb>
                            <CalcMass>41.053337755734255</CalcMass>
                            <CalcCG>6.35</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>12.7</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>14</SerialNo>
                            <OD>127.0</OD>
                            <ID>102.235</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>544.3106208</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock Cord</Name>
                            <KnownCG>368.3</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>368.3</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>121.92</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>15</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <LaunchLug>
                            <KnownMass>0.46833732166324843</KnownMass>
                            <Density>1049.21</Density>
                            <Material>Polystyrene PS</Material>
                            <Name>Rail Button</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>19.05</Xb>
                            <CalcMass>0.46833732166324843</CalcMass>
                            <CalcCG>7.9375</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>1.0472</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>15.875</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>16</SerialNo>
                            <OD>9.950199999999999</OD>
                            <ID>7.9502</ID>
                        </LaunchLug>
                        <LaunchLug>
                            <KnownMass>0.46833732166324843</KnownMass>
                            <Density>1049.21</Density>
                            <Material>Polystyrene PS</Material>
                            <Name>Rail Button</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>762.0</Xb>
                            <CalcMass>0.46833732166324843</CalcMass>
                            <CalcCG>7.9375</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>1.0472</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>15.875</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>17</SerialNo>
                            <OD>9.950199999999999</OD>
                            <ID>7.9502</ID>
                        </LaunchLug>
                        <FinSet>
                            <KnownMass>1223.86</KnownMass>
                            <Density>1909.91</Density>
                            <Material>G10 fiberglass</Material>
                            <Name>Fin set</Name>
                            <KnownCG>284.409</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>12.7</Xb>
                            <CalcMass>1040.2785664815185</CalcMass>
                            <CalcCG>284.409</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>18</SerialNo>
                            <FinCount>3</FinCount>
                            <RootChord>472.44</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>161.29</SemiSpan>
                            <SweepDistance>406.4</SweepDistance>
                            <Thickness>4.7625</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>2</TipShapeCode>
                            <TabLength>472.44</TabLength>
                            <TabDepth>14.2875</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>